name: Push changes
description: Commit and Push changes made to the workspace

inputs:
    message:
        description: Commit message to use for the commit
        required: true
        type: string

runs:
    using: "composite"
    steps:
        - name: Setup git
          shell: bash
          run: |
              git config user.name github-actions
              git config user.email github-actions@github.com
        - name: Commit
          shell: bash
          env:
              COMMIT_MESSAGE: ${{ inputs.message }}
          run: |
              git add .
              git status
              git commit -m "$COMMIT_MESSAGE"
        - name: Push
          shell: bash
          run: |
              git push origin HEAD:$GITHUB_REF_NAME
